### ISSUE TITLE
Error: Cannot find module 'azure-pipelines-task-lib/task'

### ISSUE THREAD

**Issue by peter-bloomfield** [jfrog/artifactory-azure-devops-extension#206]
Our pipeline is suddenly failing with this error every time we try to run it:

```
2020-09-30T16:19:58.9505110Z ##[section]Starting: Configure Conan
2020-09-30T16:19:58.9513990Z ==============================================================================
2020-09-30T16:19:58.9514370Z Task         : Artifactory Conan
2020-09-30T16:19:58.9514690Z Description  : This task runs a Conan command.
2020-09-30T16:19:58.9514960Z Version      : 1.10.3
2020-09-30T16:19:58.9515230Z Author       : JFrog
2020-09-30T16:19:58.9515500Z Help         : Run Conan command.
2020-09-30T16:19:58.9515850Z ==============================================================================
2020-09-30T16:19:59.0278470Z module.js:478
2020-09-30T16:19:59.0279000Z     throw err;
2020-09-30T16:19:59.0279230Z     ^
2020-09-30T16:19:59.0279470Z 
2020-09-30T16:19:59.0280700Z Error: Cannot find module 'azure-pipelines-task-lib/task'
2020-09-30T16:19:59.0281090Z     at Function.Module._resolveFilename (module.js:476:15)
2020-09-30T16:19:59.0281530Z     at Function.Module._load (module.js:424:25)
2020-09-30T16:19:59.0281850Z     at Module.require (module.js:504:17)
2020-09-30T16:19:59.0282380Z     at require (internal/module.js:20:19)
2020-09-30T16:19:59.0283300Z     at Object.<anonymous> (/Users/runner/work/_tasks/ArtifactoryConan_2b8ef770-9bc6-4394-aa81-197d0759e9c8/1.10.3/conanUtils.js:1:74)
2020-09-30T16:19:59.0283790Z     at Module._compile (module.js:577:32)
2020-09-30T16:19:59.0284230Z     at Object.Module._extensions..js (module.js:586:10)
2020-09-30T16:19:59.0284600Z     at Module.load (module.js:494:32)
2020-09-30T16:19:59.0284940Z     at tryModuleLoad (module.js:453:12)
2020-09-30T16:19:59.0285600Z     at Function.Module._load (module.js:445:3)
2020-09-30T16:19:59.0473920Z ##[error]Exit code 1 returned from process: file name '/Users/runner/runners/2.175.2/externals/node/bin/node', arguments '"/Users/runner/work/_tasks/ArtifactoryConan_2b8ef770-9bc6-4394-aa81-197d0759e9c8/1.10.3/conanBuild.js"'.
2020-09-30T16:19:59.0490350Z ##[section]Finishing: Configure Conan
```

Here's the pipeline task it's failing on:

```
- task: ArtifactoryConan@1
  inputs:
    conanCommand: 'Custom'
    customArguments: 'config install ./conan-config'
  displayName: Configure Conan
```

It looks like a recurrence of this issue: https://github.com/jfrog/artifactory-azure-devops-extension/issues/149

**Comment by JDinis** [comment]
Still happening on version 1.10.4

`Starting: Artifactory Generic Upload
==============================================================================
Task         : Artifactory Generic Upload
Description  : Upload build artifacts to Artifactory using FileSpecs while allowing to collect build-info. The collected build-info can be later published to Artifactory by the "Artifactory Publish Build Info" task.
Version      : 1.10.4
Author       : JFrog
Help         : 
==============================================================================
module.js:478
    throw err;
    ^

Error: Cannot find module 'azure-pipelines-task-lib/task'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\agent\vsts-agent-win-x64-2.148.0\_work\_tasks\ArtifactoryGenericUpload_07fc5c20-6772-11e5-abde-6901d3d00475\1.10.4\uploadArtifacts.js:1:74)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
##[error]Exit code 1 returned from process: file name 'C:\agent\vsts-agent-win-x64-2.148.0\externals\node\bin\node.exe', arguments '"C:\agent\vsts-agent-win-x64-2.148.0\_work\_tasks\ArtifactoryGenericUpload_07fc5c20-6772-11e5-abde-6901d3d00475\1.10.4\uploadArtifacts.js"'.
Finishing: Artifactory Generic Upload
`

**Comment by AndyWardUST** [comment]
Identical issue here

Starting: Install jFrog Client from Artifactory 
============================================================================== 
Task : Artifactory Tools Installer 
Description : Installs tools necessary for all Artifactory integration tasks. 
Version : 1.10.4 
Author : JFrog 
Help : 
============================================================================== 
module.js:478 
throw err; 
^ 
Error: Cannot find module 'azure-pipelines-task-lib/task' 
at Function.Module._resolveFilename (module.js:476:15) 
at Function.Module._load (module.js:424:25) 
at Module.require (module.js:504:17) 
at require (internal/module.js:20:19) 
at Object.<anonymous> (/azp/agent/_work/_tasks/ArtifactoryToolsInstaller_5916aacf-ed6c-4580-bf28-cf4b21c2b521/1.10.4/toolsInstaller.js:1:74) 
at Module._compile (module.js:577:32) 
at Object.Module._extensions..js (module.js:586:10) 
at Module.load (module.js:494:32) 
at tryModuleLoad (module.js:453:12) 
at Function.Module._load (module.js:445:3) 
##[error]Exit code 1 returned from process: file name '/azp/agent/externals/node/bin/node', arguments '"/azp/agent/_work/_tasks/ArtifactoryToolsInstaller_5916aacf-ed6c-4580-bf28-cf4b21c2b521/1.10.4/toolsInstaller.js"'. 
Finishing: Install jFrog Client from Artifactory

**Comment by eyalbe4** [comment]
All -
Thanks for posting this! 
We're working on fixing this issue ASAP. We'll send out an update soon.

**Comment by RobiNino** [comment]
Version 1.10.5 was now released and the issue was fixed.
Please refresh or reinstall the extension if it doesn't automatically update.
We are incredibly sorry about the inconvenience caused by this issue.

**Comment by AndyWardUST** [comment]
Thanks for the fast fix

**Comment by JDinis** [comment]
Thanks, its also working for me :) :shipit: 👍

**Comment by darren271** [comment]
> Version 1.10.5 was now released and the issue was fixed.
> Please refresh or reinstall the extension if it doesn't automatically update.
> We are incredibly sorry about the inconvenience caused by this issue.

How do you "refresh"? I'm afraid that if I remove/reinstall that I will end up having to redo all the YAML pipelines that refer to the integration. How often does an auto-refresh happen? 
![Screen Shot 2020-09-30 at 4 13 35 PM](https://user-images.githubusercontent.com/55906127/94734926-f09f7a00-0337-11eb-9b2d-582e0acdf5f1.png)

**Comment by eyalbe4** [comment]
@darren271,
The extension is supposed to get upgraded immediately. I'm not sure why it hasn't updated. I believe this is out of the control of the extension itself...
I'm just guessing here - Have you tried signing out and the signing in again? Maybe trying to reinstalling it from the marketplace would help?

**Comment by eyalbe4** [comment]
@darren271,
Were you able to resolve the issue? Here's a report of another issue where the extension didn't upgeade automatically -
https://github.com/jfrog/artifactory-azure-devops-extension/issues/207
If you managed to come across a solution for the issue, this may help others. Thanks!

**Comment by darren271** [comment]
> @darren271,
> The extension is supposed to get upgraded immediately. I'm not sure why it hasn't updated. I believe this is out of the control of the extension itself...
> I'm just guessing here - Have you tried signing out and the signing in again? Maybe trying to reinstalling it from the marketplace would help?

I tried signing out as well as disabling and re-enabling to no avail. Uninstalling and reinstalling did the trick and didn't cause failures or changes to the jobs as I anticipated.

**Comment by eyalbe4** [comment]
Thanks you all for sharing this information.
I've just added a comment in https://github.com/jfrog/artifactory-azure-devops-extension/issues/207 summarising the issue. If needed, let's continue the discussion there.
