### ISSUE TITLE
Artifactory Generic Download failing after extension was  update to  1.11.1 

### ISSUE THREAD

**Issue by boris-ait** [jfrog/artifactory-azure-devops-extension#224]
**Describe the bug**

Got below errors in Artifactory Generic Download

2020-12-21T10:59:59.6108197Z   "status": "failure",
2020-12-21T10:59:59.6109847Z [Error] rename C:\Users\VSSADM~1\AppData\Local\Temp\jfrog.cli.temp.-1608548399-979236064\Install-SeaMonkey.ps1 D:\a\1\s\arm\Install-SeaMonkey.ps1: The system cannot move the file to a different disk drive.
2020-12-21T10:59:59.6114442Z   "totals": {
2020-12-21T10:59:59.6116218Z [Error] Download finished with errors, please review the logs.
2020-12-21T10:59:59.6121498Z     "success": 0,
2020-12-21T10:59:59.6148744Z     "failure": 1
2020-12-21T10:59:59.6149610Z   }
2020-12-21T10:59:59.6162384Z }
2020-12-21T10:59:59.6218839Z ##[error]Error: Command failed: C:\hostedtoolcache\windows\jfrog\1.42.2\x64\jfrog.exe rt dl --url="https://**" --user=*** --password=*** --fail-no-op=true --dry-run=false --insecure-tls=false --threads=3 --retries=3 --validate-symlinks=false --split-count=3 --min-split=5120
2020-12-21T10:59:59.6411285Z ##[section]Finishing: Download Artifacts - Arm

**To Reproduce**
Use Artifactory Generic Download task with below spec:

- task: ArtifactoryGenericDownload@3
  displayName: ${{ parameters.jobName }}
  inputs:
    connection: ${{ parameters.ArtifactoryServiceName }}
    fileSpec: |
     {
         "files": [
          {
             "pattern": "${{ parameters.patternPath }}/*.zip",
             "target": "${{ parameters.target }}\",
             "build": "${{ parameters.buildName }}/${{ parameters.buildID }}",
             "flat":"true",
             "explode":"true"
          }
         ]
     }

**Expected behavior**
Finish task without errors

**Screenshots**

**Versions**
- Artifactory Azure DevOps extension version: 1.11.1
- Agent operating system: Hosted agent, Image: windows-2019
- JFrog Artifactory version: SaaS Artifactory

**Additional context**
Full log of the  task:
2020-12-21T10:59:55.8429101Z ##[section]Starting: Download Artifacts - Arm
2020-12-21T10:59:55.8591115Z ==============================================================================
2020-12-21T10:59:55.8591676Z Task         : Artifactory Generic Download
2020-12-21T10:59:55.8592231Z Description  : Download artifacts from Artifactory using FileSpecs, while allowing to collect build-info. The collected build-info can be later published to Artifactory by the "Artifactory Publish Build Info" task.
2020-12-21T10:59:55.8593687Z Version      : 3.11.1
2020-12-21T10:59:55.8594098Z Author       : JFrog
2020-12-21T10:59:55.8594345Z Help         : 
2020-12-21T10:59:55.8594763Z ==============================================================================
2020-12-21T10:59:56.2408362Z Downloading: https://api.bintray.com/content/jfrog/jfrog-cli-go/1.42.2/jfrog-cli-windows-amd64/jfrog.exe?bt_package=jfrog-cli-windows-amd64
2020-12-21T10:59:57.9753947Z Caching tool: jfrog 1.42.2 x64
2020-12-21T10:59:57.9996132Z Running jfrog-cli from C:\hostedtoolcache\windows\jfrog\1.42.2\x64\jfrog.exe.
2020-12-21T10:59:58.3255150Z JFrog CLI version: 1.42.2
2020-12-21T10:59:58.3266261Z Generic download...
2020-12-21T10:59:58.3283467Z Using file spec:
2020-12-21T10:59:58.3283921Z {
2020-12-21T10:59:58.3284226Z     "files": [
2020-12-21T10:59:58.3284577Z      {
2020-12-21T10:59:58.3284971Z         "pattern": "aqua-saas/SeaMonkey/*.zip",
2020-12-21T10:59:58.3285410Z         "target": "D:\\a\\1\\s/arm\\",
2020-12-21T10:59:58.3285844Z         "build": "farmerui-arm/LATEST",
2020-12-21T10:59:58.3286237Z         "flat":"true",
2020-12-21T10:59:58.3286602Z         "explode":"true"
2020-12-21T10:59:58.3286918Z      }
2020-12-21T10:59:58.3287209Z     ]
2020-12-21T10:59:58.3287490Z }
2020-12-21T10:59:58.4152684Z [Info] Searching items to download...
2020-12-21T10:59:58.9468453Z [Info] [Thread 2] Downloading aqua-local-saas/SeaMonkey/SeaMonkey.Automation-1.1.1.2.zip
2020-12-21T10:59:59.0803729Z [Info] [Thread 2] Extracting archive: D:\a\1\s\arm\SeaMonkey.Automation-1.1.1.2.zip to D:\a\1\s\arm\
2020-12-21T10:59:59.1040997Z [Warn] [Thread 2] Attempt 0 - Failure occurred while downloading https://*****/aqua-local-saas/SeaMonkey/SeaMonkey.Automation-1.1.1.2.zip - rename C:\Users\VSSADM~1\AppData\Local\Temp\jfrog.cli.temp.-1608548399-812474715\Install-SeaMonkey.ps1 D:\a\1\s\arm\Install-SeaMonkey.ps1: The system cannot move the file to a different disk drive.
2020-12-21T10:59:59.2362089Z [Info] [Thread 2] Extracting archive: D:\a\1\s\arm\SeaMonkey.Automation-1.1.1.2.zip to D:\a\1\s\arm\
2020-12-21T10:59:59.2589301Z [Warn] [Thread 2] Attempt 1 - Failure occurred while downloading https://****/aqua-local-saas/SeaMonkey/SeaMonkey.Automation-1.1.1.2.zip - rename C:\Users\VSSADM~1\AppData\Local\Temp\jfrog.cli.temp.-1608548399-740628222\Install-SeaMonkey.ps1 D:\a\1\s\arm\Install-SeaMonkey.ps1: The system cannot move the file to a different disk drive.
2020-12-21T10:59:59.4142969Z [Info] [Thread 2] Extracting archive: D:\a\1\s\arm\SeaMonkey.Automation-1.1.1.2.zip to D:\a\1\s\arm\
2020-12-21T10:59:59.4377504Z [Warn] [Thread 2] Attempt 2 - Failure occurred while downloading https://***/aqua-local-saas/SeaMonkey/SeaMonkey.Automation-1.1.1.2.zip - rename C:\Users\VSSADM~1\AppData\Local\Temp\jfrog.cli.temp.-1608548399-526257221\Install-SeaMonkey.ps1 D:\a\1\s\arm\Install-SeaMonkey.ps1: The system cannot move the file to a different disk drive.
2020-12-21T10:59:59.5821694Z [Info] [Thread 2] Extracting archive: D:\a\1\s\arm\SeaMonkey.Automation-1.1.1.2.zip to D:\a\1\s\arm\
2020-12-21T10:59:59.6073593Z [Warn] [Thread 2] Attempt 3 - Failure occurred while downloading https://****aqua-local-saas/SeaMonkey/SeaMonkey.Automation-1.1.1.2.zip - rename C:\Users\VSSADM~1\AppData\Local\Temp\jfrog.cli.temp.-1608548399-979236064\Install-SeaMonkey.ps1 D:\a\1\s\arm\Install-SeaMonkey.ps1: The system cannot move the file to a different disk drive.
2020-12-21T10:59:59.6080425Z {
2020-12-21T10:59:59.6082757Z [Error] [Thread 2]  Received an error: rename C:\Users\VSSADM~1\AppData\Local\Temp\jfrog.cli.temp.-1608548399-979236064\Install-SeaMonkey.ps1 D:\a\1\s\arm\Install-SeaMonkey.ps1: The system cannot move the file to a different disk drive.
2020-12-21T10:59:59.6108197Z   "status": "failure",
2020-12-21T10:59:59.6109847Z [Error] rename C:\Users\VSSADM~1\AppData\Local\Temp\jfrog.cli.temp.-1608548399-979236064\Install-SeaMonkey.ps1 D:\a\1\s\arm\Install-SeaMonkey.ps1: The system cannot move the file to a different disk drive.
2020-12-21T10:59:59.6114442Z   "totals": {
2020-12-21T10:59:59.6116218Z [Error] Download finished with errors, please review the logs.
2020-12-21T10:59:59.6121498Z     "success": 0,
2020-12-21T10:59:59.6148744Z     "failure": 1
2020-12-21T10:59:59.6149610Z   }
2020-12-21T10:59:59.6162384Z }
2020-12-21T10:59:59.6218839Z ##[error]Error: Command failed: C:\hostedtoolcache\windows\jfrog\1.42.2\x64\jfrog.exe rt dl --url="https://*******" --user=*** --password=*** --fail-no-op=true --dry-run=false --insecure-tls=false --threads=3 --retries=3 --validate-symlinks=false --split-count=3 --min-split=5120

**Comment by eyalbe4** [comment]
@boris-ait - thanks for reporting this!
We've just released version 1.11.2 - I belive this should resolve the issue.
Please let su know.

**Comment by DO-User** [comment]
Hi @eyalbe4,
It seems the issue occurs when we use the jfrog-cli 1.42.3
Anyway, it works with jfrog-cli 1.41.x and I found that @talarian1 did the cli change 5 days ago:
https://github.com/jfrog/artifactory-azure-devops-extension/commit/0ce4a38cf199bebc6bed00f337e871817a71cb49

Also, we face the same issue when the target in the task is "." (dot).
It is a severe issue that blocks us to execute our builds!!
Please assist ASAP!!

**Comment by DO-User** [comment]
> @boris-ait - thanks for reporting this!
> We've just released version 1.11.2 - I belive this should resolve the issue.
> Please let us know.

We have the same issue using this version.
Please see the comment above. We did some debugging and found the issue in the jfrog-cli version.

**Comment by eyalbe4** [comment]
@DO-User,
Can you please share the AzureDevOps build log? I'd like to see if indeed the pipeline downloads version 1.42.3.
The original build log you shared still downloads version 1.42.2.

**Comment by DO-User** [comment]
I'm sharing with you the second scenario on Linux machine:

`Starting: ArtifactoryGenericDownload
==============================================================================
Task         : Artifactory Generic Download
Description  : Download artifacts from Artifactory using FileSpecs, while allowing to collect build-info. The collected build-info can be later published to Artifactory by the "Artifactory Publish Build Info" task.
Version      : 3.11.2
Author       : JFrog
Help         : 
==============================================================================
Downloading: https://api.bintray.com/content/jfrog/jfrog-cli-go/1.42.3/jfrog-cli-linux-amd64/jfrog?bt_package=jfrog-cli-linux-amd64
Caching tool: jfrog 1.42.3 x64
Running jfrog-cli from /home/buser/ag04/_work/_tool/jfrog/1.42.3/x64/jfrog.
JFrog CLI version: 1.42.3
Generic download...
Using file spec:
{ "files": [ { "pattern": "generic-p/p-modules/modules-1.0.0.tar.gz", "target": ".", "explode": "true" } ] }
[Info] Searching items to download...
[Info] [Thread 2] Downloading generic-p/p-modules/modules-1.0.0.tar.gz
[Info] [Thread 2] [2]: 206 Partial Content...
[Info] [Thread 2] [0]: 206 Partial Content...
[Info] [Thread 2] [1]: 206 Partial Content...
[Error] [Thread 2]  Received an error: open p-modules/modules-1.0.0.tar.gz: not a directory
{
  "status": "failure",
  "totals": {
    "success": 0,
    "failure": 1
[Error] open p-modules/modules-1.0.0.tar.gz: not a directory
[Error] Download finished with errors, please review the logs.
  }
}
##[error]Error: Command failed: /home/buser/ag04/_work/_tool/jfrog/1.42.3/x64/jfrog rt dl --url="https://artifactory.blablabla.com/artifactory" --user=*** --password=*** --fail-no-op=true --dry-run=false --insecure-tls=false --threads=3 --retries=3 --validate-symlinks=false --split-count=3 --min-split=5120
Finishing: ArtifactoryGenericDownload
`

**Comment by Or-Geva** [comment]
@DO-User , Please run the job with env var `JFROG_CLI_ERROR_HANDLING=panic` to get the full stack trace.

**Comment by boris-ait** [comment]
For me, the new version of the extension worked well.
If we will face another issue on Linux platform, a new issue will be opened.

**Comment by AlexeiBarabash** [comment]
> @DO-User , Please run the job with env var `JFROG_CLI_ERROR_HANDLING=panic` to get the full stack trace.

Here is the output : 

Task         : Artifactory Generic Download
Description  : Download artifacts from Artifactory using FileSpecs, while allowing to collect build-info. The collected build-info can be later published to Artifactory by the "Artifactory Publish Build Info" task.
Version      : 3.11.2
Author       : JFrog
Help         : 
==============================================================================
Found tool in cache: jfrog 1.42.3 x64
Running jfrog-cli from /home/build_user/ag01/_work/_tool/jfrog/1.42.3/x64/jfrog.
JFrog CLI version: 1.42.3
Generic download...
Using file spec:
{ "files": [ { "pattern": "generic/modules/modules-1.0.0.tar.gz", "target": ".", "explode": "true" } ] }
[Info] Searching items to download...
[Info] [Thread 2] Downloading generic/modules/modules-1.0.0.tar.gz
[Info] [Thread 2] [2]: 206 Partial Content...
[Info] [Thread 2] [1]: 206 Partial Content...
[Info] [Thread 2] [0]: 206 Partial Content...
{
  "status": "failure",
  "totals": {
    "success": 0,
    "failure": 1
  }
}
panic: open modules/modules-1.0.0.tar.gz: not a directory

goroutine 11 [running]:
github.com/jfrog/jfrog-cli-core/utils/coreutils.PanicOnError(0x104fd40, 0xc000186480, 0x242, 0x1b6)
	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-core@v1.2.4/utils/coreutils/utils.go:68 +0x59
github.com/jfrog/jfrog-client-go/utils/io/fileutils.MoveFile(0xc00045a090, 0xd, 0xc0004d2360, 0x22, 0x104fd40, 0xc000186480)
	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.17.4/utils/io/fileutils/files.go:593 +0x40c
github.com/jfrog/jfrog-client-go/utils.ExtractArchive(0xc000446610, 0xd, 0xc00045a090, 0xd, 0xc000434620, 0x14, 0xc000436130, 0xb, 0x30, 0xc00045a090)
	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.17.4/utils/archiveutils.go:34 +0x477
github.com/jfrog/jfrog-client-go/httpclient.(*HttpClient).DownloadFileConcurrently(0xc000450680, 0xc000434620, 0x14, 0xc0004d03c0, 0x5d, 0xc000468570, 0x30, 0xc00045a090, 0xd, 0xc000446610, ...)
	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.17.4/httpclient/client.go:428 +0x48a
github.com/jfrog/jfrog-client-go/artifactory/httpclient.(*ArtifactoryHttpClient).DownloadFileConcurrently(0xc00021bc10, 0xc000434620, 0x14, 0xc0004d03c0, 0x5d, 0xc000468570, 0x30, 0x16b9fce, 0x1, 0xc000446610, ...)
	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.17.4/artifactory/httpclient/httpclient.go:125 +0x158
github.com/jfrog/jfrog-client-go/artifactory/services.(*DownloadService).downloadFile(0xc0002d67c0, 0xc000180460, 0xc000436130, 0xb, 0xc00019e500, 0x1000001, 0x1400, 0x3, 0x3, 0xd, ...)
	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.17.4/artifactory/services/download.go:265 +0x472
github.com/jfrog/jfrog-client-go/artifactory/services.(*DownloadService).downloadFileIfNeeded(0xc0002d67c0, 0xc0004d03c0, 0x5d, 0xc000446610, 0xd, 0x16b9fce, 0x1, 0xc000436130, 0xb, 0xc000446620, ...)
	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.17.4/artifactory/services/download.go:413 +0x382
github.com/jfrog/jfrog-client-go/artifactory/services.(*DownloadService).createFileHandlerFunc.func1.1(0x2, 0xc00004ef80, 0x1)
	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.17.4/artifactory/services/download.go:386 +0x808
github.com/jfrog/gofrog/parallel.(*runner).Run.func1(0xc00046a1c0, 0xc0005d6c60, 0xc00046a1d0, 0xc00046a1e0, 0x2)
	/root/go/pkg/mod/github.com/jfrog/gofrog@v1.0.6/parallel/runner.go:111 +0xb1
created by github.com/jfrog/gofrog/parallel.(*runner).Run
	/root/go/pkg/mod/github.com/jfrog/gofrog@v1.0.6/parallel/runner.go:108 +0xd9

**Comment by eyalbe4** [comment]
@DO-User - thanks for providing the stacktrace.
We're unable to replicate this issue. We tried creating the exact same spec from your logs:
```
{ "files": [ { "pattern": "generic/modules/modules-1.0.0.tar.gz", "target": ".", "explode": "true" } ] }
```
and we get no errors.
Maybe there's something in the structure of your **modules-1.0.0.tar.gz** that causes this. Will you be able to share this file with us, so we can reproduce this behaviour?
Let me create a command that you can use to send us this file...

**Comment by eyalbe4** [comment]
@@DO-User,
If you **are allowed** to share with us the **modules-1.0.0.tar.gz** file, then you run the following JFrog CLI command while inside a directory containing the **modules-1.0.0.tar.gz** file. It will upload this file to a repository where we can fetch it from.
```
jfrog rt u modules-1.0.0.tar.gz t1 --url https://ecosysjfrog.jfrog.io/artifactory --access-token eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJ2MUFpWkIySDFMakllYXY2aHRoRXZST1NHYktpM2N3b3IwbEgtX0h4ZnBnIn0.eyJzdWIiOiJqZi1hcnRpZmFjdG9yeUAzMDNmMThjNC0yYzc4LTRiOGEtYWNjMi03M2FkMjhmMTE1MjBcL3VzZXJzXC9odHRwczpcL1wvZWNvc3lzamZyb2cuamZyb2cuaW9cL2FydGlmYWN0b3J5XC8iLCJzY3AiOiJtZW1iZXItb2YtZ3JvdXBzOnQxIGFwaToqIiwiYXVkIjoiamYtYXJ0aWZhY3RvcnlAMzAzZjE4YzQtMmM3OC00YjhhLWFjYzItNzNhZDI4ZjExNTIwIiwiaXNzIjoiamYtYXJ0aWZhY3RvcnlAMzAzZjE4YzQtMmM3OC00YjhhLWFjYzItNzNhZDI4ZjExNTIwXC91c2Vyc1wvZXlhbGIiLCJleHAiOjE2MDg2MTUyNjYsImlhdCI6MTYwODU3OTI2NiwianRpIjoiZmE1NmJkNjEtMzgzNy00YjgzLTlhZGMtZjU3NGYxZDNiZTdhIn0.N_1xYFF4uIax83wBEDrVC0_MOl2vbb2drrrPeRm9bidxMbDF9KsMA-sUKTq2qh5Bg03Eko4KntNjLZVD9_WucsSvXaEMdJu4nr4N953vxuaK3MSUkFK5PSZlH4WQsFgLxjyQSDnnFGXiMIsN41X3S9TGfsWqWRDmwRVRE6-npCRcEtHFABYG5mcuvcUDqsIIxl6KCzNHuHyx9lHbK-h0cqE8QSezE6G45zL9JH5jQ9NWjF8NSizV0Vbreus7KC9kmKnJQ7pGDTDkA6fEpMsHDE8kQLILfv2xbcZBbIGo9hHi12m8d00jXpnuQlBIKGfdL1nlnNMV222DfMWvYUl_4g
```

**Comment by AlexeiBarabash** [comment]
@eyalbe4 , thx for the reply . 
this task was working ok till yesterday . 
from what we found : 
it stopped working with the new jfrog-cli 
`jfrog-cli` version `1.42.x` has stopped working with `"." as target`  and `"explode=true"`
if you change the target with `"./"` its working. 
`jfrog-cli` version `1.41.2` this behavior is disappearing and the task is working correctly.

the content of `modules-1.0.0.tar.gz` is folders with number of folders.(nothing special). 
for example : 
com/
system/
redis/

that should be extracted to modules/[com,system,redis] (also it created the folder modules).

**Comment by eyalbe4** [comment]
I'm happy to hear this is working for you now @AlexeiBarabash!
Appologies for the inconinicence caused by this issue.
@Or-Geva shared with me that he managed to repruce the issue. We decided to enhance the testing scneios as part of the JFrog CLI's testing code around the explode functionality. We want to make sure this farly complex functionality is fully covered.
We're also working on making some design chamges to the code, which should simplify it and make it safer to maintain.

**Comment by DO-User** [comment]
Hi @eyalbe4,
Maybe we didn't explain it clearly, but the usage of "." as a target path is still not manageable.
We had to modify our pipelines in order to fix this syntax issue.
Anyway, we've already made the adjustments on our side, and I glad to hear that you thick your tests for the Jfrog CLI.

Thanks.
