### ISSUE TITLE
Artifactory Generic Upload task fails 

### ISSUE THREAD

**Issue by svetoslavs** [jfrog/artifactory-azure-devops-extension#239]
**Describe the bug**
I am using the Artifactory Generic Upload task in an Azure DevOps piipeline for quite a while, and suddenly, without any change to the pipeline itself, it started failing.
Failures started on April 12th, initially the error was:
```
##[error]Error occurred while executing task:
Failed while attempting to download JFrog CLI from https://api.bintray.com/content/jfrog/jfrog-cli-go/1.42.3/jfrog-cli-windows-amd64/jfrog.exe?bt_package=jfrog-cli-windows-amd64. If this build agent cannot access the internet, you may use the 'Artifactory Tools Installer' task, to download JFrog CLI through an Artifactory repository, which proxies 
Error: Unexpected HTTP response: 403
```

Next morning, the error changed to:
```
[Error] refname "214f451aba1053be608f2096b71f90d7584a5789" is ambiguous
[Error] refname "214f451aba1053be608f2096b71f90d7584a5789" is ambiguous
{
  "status": "failure",
[Error] Upload finished with errors, Please review the logs.
  "totals": {
    "success": 0,
    "failure": 0
  }
}
```

where 214f451aba1053be608f2096b71f90d7584a5789 is the last commit in the repo (it is not clear what does it have to do with the upload task).

Tried both with V1 and V2 of the task, same error.

This is what we got when setting "JFROG_CLI_ERROR_HANDLING" to "panic":
```
goroutine 23 [running]:
github.com/jfrog/jfrog-cli-core/utils/coreutils.PanicOnError(0x11046c0, 0xc00089c3c0, 0x28, 0x18bf900)
	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-core@v1.5.0/utils/coreutils/utils.go:85 +0x60
github.com/jfrog/jfrog-client-go/utils.(*manager).readMessage(0xc0000b3958)
	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.21.0/utils/git.go:294 +0x16c
github.com/jfrog/jfrog-client-go/utils.(*manager).ReadConfig(0xc0000b3958, 0x2, 0x2)
	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.21.0/utils/git.go:46 +0x8f
github.com/jfrog/jfrog-client-go/utils.extractGitDetails(0xc000814080, 0x2, 0x0, 0xc000814101, 0x6, 0xde26c0, 0xc0000b3a28, 0x0, 0x0, 0xc000814100)
	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.21.0/utils/vcsdetails.go:103 +0xef
github.com/jfrog/jfrog-client-go/utils.tryGetGitDetails(0xc000814080, 0x2, 0x2, 0x0, 0x0, 0xc000814080, 0x2, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.21.0/utils/vcsdetails.go:96 +0xca
github.com/jfrog/jfrog-client-go/utils.(*VcsCache).GetVcsDetails(0xc00006a120, 0xc000814080, 0xf, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.21.0/utils/vcsdetails.go:65 +0x1fd
github.com/jfrog/jfrog-client-go/artifactory/services.getVcsProps(0xc000886000, 0x44, 0xc00006a120, 0x60, 0x0, 0x0, 0xc00042ab40)
	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.21.0/artifactory/services/upload.go:825 +0x96
github.com/jfrog/jfrog-client-go/artifactory/services.collectFilesForUpload(0xc00042ab40, 0x0, 0x0, 0xc0005f0af0, 0x63, 0x1010000, 0x3, 0x2800, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.21.0/artifactory/services/upload.go:240 +0x5a2
github.com/jfrog/jfrog-client-go/artifactory/services.(*UploadService).prepareUploadTasks.func1(0x111f4c0, 0xc00064a3c0, 0xc0005c9cc0, 0x1, 0x1, 0xc0000be208, 0xc0005c9d10, 0xc00064a390)
	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.21.0/artifactory/services/upload.go:119 +0x251
created by github.com/jfrog/jfrog-client-go/artifactory/services.(*UploadService).prepareUploadTasks
	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.21.0/artifactory/services/upload.go:103 +0x9c
```

This is the command executed in the log for V1
```
##[error]Error: Command failed: C:\hostedtoolcache\windows\jfrog\1.46.1\x64\jfrog.exe rt u --url="<--my-url-here-->" --spec="D:\a\1\s\uploadSpec1618309752855.json" --user=*** --password=***
```

This is the command executed in the log for V2
```
##[error]Error: Command failed: C:\hostedtoolcache\windows\jfrog\1.46.1\x64\jfrog.exe rt u --url="<--my-url-here-->" --user=*** --password=*** --fail-no-op=true --dry-run=false --insecure-tls=false --threads=3 --retries=3 --symlinks=false
```

**To Reproduce**
Use the Artifactory Generic Upload task in a pipeline, either V1, or V2. 
```yml
- task: ArtifactoryGenericUpload@2
  displayName: 'Artifactory Generic Upload'
  inputs:
    artifactoryService: 'my jfrog service'
    specSource: 'taskConfiguration'
    fileSpec: |
     {
       "files": [
         {
           "pattern": "my-zip-file-name.zip",
           "target": "location/in/artifactory/"
         }
       ]
     }
    collectBuildInfo: true
```

**Expected behavior**
Expected the task to continue working as before.

**Versions**
- Artifactory Azure DevOps extension version: 1.11.6
- Agent operating system: windows-latest (hosted agent)
- JFrog Artifactory version: using hosted solution as a service (*.jfrog.io)

**Comment by philthethrill99** [comment]
same issue here

**Comment by eyalbe4** [comment]
Thanks for sharing this information!
We're looking into this issue. As a temporary workaround, try disabling the build-info collection for this task. Please let me know if this avoids this error.

**Comment by philthethrill99** [comment]
Same error in jfrog-cli command line when trying _jfrog rt bp_....

**Comment by eyalbe4** [comment]
Which OS are you getting this error on @philthethrill99?

**Comment by philthethrill99** [comment]
linux ubuntu 20.04 wsl2

**Comment by philthethrill99** [comment]
jfrog rt build-publish buildName buildNumber
[Error] open /tmp/jfrog/builds/a2V5Y2xvYWstaW50ZWdyYXRpb24tdGVzdGluZy1wbGF5Ym9va3NfMjAyMTA0MTQuMS4xLjEt/partials/details: no such file or directory

**Comment by svetoslavs** [comment]
@eyalbe4 disabling build-info collection avoids the error, but it can only be a temporary workaround, build-info collection is needed.

**Comment by philthethrill99** [comment]
Sorry wrong info. The error comes from bash command and Artifactory tasks in Azure DevOps pipeline on a ubuntu-18.04 hosted agent

**Comment by eyalbe4** [comment]
@philthethrill99 - the error you shared is different than the one initially shared in this issue. Your error hints to the situation where the the build is published to Artifactory, where no tasks which collect build-info came before it, or the tasks before it used an older version of jfrog-cli.

**Comment by philthethrill99** [comment]
```
==============================================================================
Task         : Artifactory Generic Upload
Description  : Upload build artifacts to Artifactory using FileSpecs while allowing to collect build-info. The collected build-info can be later published to Artifactory by the "Artifactory Publish Build Info" task.
Version      : 2.11.6
Author       : JFrog
Help         : 
==============================================================================
Downloading: https://releases.jfrog.io/artifactory/jfrog-cli/v1/1.46.1/jfrog-cli-linux-amd64/jfrog?bt_package=jfrog-cli-linux-amd64
Caching tool: jfrog 1.46.1 x64
Running jfrog-cli from /opt/hostedtoolcache/jfrog/1.46.1/x64/jfrog.
JFrog CLI version: 1.46.1
Using file spec:
{
  "files": [
    {
      "pattern": "/home/vsts/work/1/a/playbookname-x.x.x.zip",
      "target": "libs-snapshot-local/playbook-name/x.x.x/",
      "targetProps": "build.version=x.x.x"
    }
  ]
}
panic: refname "24012e440a44c52cfda2c83b10758c8e65512122" is ambiguous

goroutine 17 [running]:
github.com/jfrog/jfrog-cli-core/utils/coreutils.PanicOnError(0x10e2200, 0xc000270320, 0x28, 0x1891e20)
	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-core@v1.5.0/utils/coreutils/utils.go:85 +0x59
github.com/jfrog/jfrog-client-go/utils.(*manager).readMessage(0xc0000eb958)
	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.21.0/utils/git.go:294 +0x165
github.com/jfrog/jfrog-client-go/utils.(*manager).ReadConfig(0xc0000eb958, 0x2, 0x2)
	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.21.0/utils/git.go:46 +0x88
github.com/jfrog/jfrog-client-go/utils.extractGitDetails(0xc0002e8050, 0x0, 0x0, 0xf2e101, 0x4, 0xdc02e0, 0xc00010ca28, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.21.0/utils/vcsdetails.go:103 +0xe8
github.com/jfrog/jfrog-client-go/utils.tryGetGitDetails(0xc0002e8050, 0x0, 0x0, 0x0, 0x0, 0xc0002e8050, 0x0, 0x8, 0x0, 0x0)
	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.21.0/utils/vcsdetails.go:96 +0xc3
github.com/jfrog/jfrog-client-go/utils.(*VcsCache).GetVcsDetails(0xc000075ce0, 0xc0002e8050, 0x13, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.21.0/utils/vcsdetails.go:65 +0x1f6
github.com/jfrog/jfrog-client-go/artifactory/services.getVcsProps(0xc0002e8050, 0x4d, 0xc000075ce0, 0xb1, 0x0, 0x0, 0xc00012a7e0)
	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.21.0/artifactory/services/upload.go:825 +0x8f
github.com/jfrog/jfrog-client-go/artifactory/services.collectFilesForUpload(0xc00012a7e0, 0x0, 0x0, 0xc00039ef00, 0x72, 0x1010000, 0x3, 0x2800, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.21.0/artifactory/services/upload.go:240 +0x59b

```

**Comment by eyalbe4** [comment]
@philthethrill99 and @svetoslavs,
This error occurs because jfrog-cli fails to read the info from inside the project's local .git directory. Will one of you be able to archive and share this directory? Any .git directory which replicates this issue will do.

**Comment by philthethrill99** [comment]
just to know, do my pattern needs to start at the root directory of project  so it can be at the same level of .git folder ? This is not my case

**Comment by eyalbe4** [comment]
@philthethrill99,
JFrog CLI searches for the .git directory in the current directory, or in an upstream directory, just like the git client.

**Comment by philthethrill99** [comment]
[azure-devops-repo-git-folder.zip](https://github.com/jfrog/artifactory-azure-devops-extension/files/6313510/azure-devops-repo-git-folder.zip)

**Comment by philthethrill99** [comment]
Still have the issue with 1.46.2

**Comment by philthethrill99** [comment]
@eyalbe4 Are you still looking into this issue ?

**Comment by philthethrill99** [comment]
The workaround with artifactoryToolsInstaller with version 1.42.3 is now working i was trying to upload from a folder that didn't have access to the .git folder.
using jfrog-cli 1.46.2 is still not working

**Comment by eyalbe4** [comment]
@philthethrill99,
We're attention to fix this issue. We'll post here an update soon.

**Comment by eyalbe4** [comment]
@@philthethrill99,,
We have a PR with a fix in progress - https://github.com/jfrog/jfrog-client-go/pull/334

**Comment by eyalbe4** [comment]
@philthethrill99,
Patch 1.11.8 includes the fix and has been released to the marketplace.
Looking forward to your feedback.

**Comment by philthethrill99** [comment]
@eyalbe4 fixed. Thank you

**Comment by svetoslavs** [comment]
@eyalbe4 from the first look at the new update it seems that it resolves it for our case as well. Thanks.

**Comment by eyalbe4** [comment]
Happy to hear this @philthethrill99 and @svetoslavs.
Thanks for your confirmation and our apologies for the inconvenience caused by this incident.
